config/routes.rb
WufooClone::Application.routes.draw do
  root :to => "static_pages#root"
  
  resource :session, :only => [:new, :create, :destroy]
  resources :users, :except => [:index]
  resources :accounts, :only => [:new, :create, :show] do
    resources :users, :only => [:index]
  end
  
  resources :forms do
    resources :fields, :except => [:index, :show]
    resources :entries, :only => [:index, :new]
  end
  
  resources :entries, :except => [:new, :index]

  post "forms/:id/duplicate", :to => "forms#duplicate", :as => "duplicate_form"
  put "users/:id/toggle", :to=> "users#toggle_admin", :as => "toggle_user"
  get "help", :to => "static_pages#help"
end

app/models/user.rb
class User
  include MongoMapper::Document
  attr_reader :password
  
  key :account_id, ObjectId, :required => true
  key :username, String, :required => true, :unique => true
  key :email, String, :required => true, :unique => true
  key :password_digest, String, :required => true
  key :session_token, String, :required => true
  key :admin, String
  
  timestamps!
  
  attr_accessible :account_id, :username, :password, :email, :admin, :forms
  
  validates_length_of :password, :minimum => 6, :allow_nil => true
  
  before_validation :ensure_session_token
  
  belongs_to :account
  
  def self.find_by_credentials(username, password)
     user = User.find_by_username(username)

     (user && user.is_password?(password)) ? user : nil
  end
  
  def password=(pass)
     @password = pass
     self.password_digest = BCrypt::Password.create(pass)
  end

  def is_password?(pass)
     BCrypt::Password.new(self.password_digest).is_password?(pass)
  end
  
  def self.generate_session_token
     SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
     self.session_token = self.class.generate_session_token
     self.save!
  end
  
  def user_type
    if account.is_creator?(id)
      return "Account creator"
    elsif admin
      return "Admin"
    end
    
    return "User"
  end
  
  private
  def ensure_session_token
      self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!
  
  def show
    @user = current_user
    render :show
  end
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    if(params[:user][:password] == params[:user][:repeat])
      params[:user][:repeat] = nil
      params[:user][:account_id] = current_account.id
      
      @user = User.new(params[:user])
      
      if @user.save
        redirect_to user_url(current_user)
      else
        flash.now[:errors] = @user.errors.full_messages
        render :new
      end
    else
      flash.now[:errors] = ["Passwords do not match"]
      @user = User.new(params[:user])
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(params[:user])
      redirect_to user_url(current_user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to user_url(current_user)
    end
  end
  
  def toggle_admin
    @user = User.find(params[:id])
    if @user.admin
      @user.update_attributes(:admin => nil)
    else
      @user.update_attributes(:admin => 't')
    end
    
    redirect_to user_url(current_user)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to user_url(current_user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
<div class="el-show">
	<h4 class= "el-title">Edit Profile</h4>
	<%= render :partial => "layouts/errors" %>

	<form class="edit-profile" action="<%= user_url(current_user) %>" method="post" accept-charset="utf-8">
		<input type="hidden" 
					 name="authenticity_token"
					 value="<%= form_authenticity_token %>">
	
		<input type="hidden" name="_method" value="put">
	
		<label for="user-username">Username: </label>
		<input type="text" name="user[username]"
					 value="<%= @user.username %>" id="user-username">
		<br>
	
		<label for="user-email">Email: </label>
		<input type="text" name="user[email]"
					 value="<%= @user.email %>" id="user-email">
		<br>
	
		<p><input class="btn" type="submit" value="Update Profile"></p>
	</form>
</div>

app/views/users/_user.html.erb
<div class="el-show">
	<h4 class= "el-title"><%= user.username %></h4>
	<ul class="inline">
		<li><%= user.user_type %></li>
		<% if current_user.admin %>
			<%  unless current_account.is_creator?(user.id) %>
				<li class="pull-right">
					<%= button_to "Delete", user_url(user), :method => :delete, :class => "btn btn-mini btn-danger" %>
				</li>
					<% if user.user_type == "User" %>
						<li class="pull-right">
							<%= button_to "Make Admin", toggle_user_url(user), :method => :put, :class => "btn btn-mini btn-primary" %>
						</li>
					<% else %>
						<li class="pull-right">
							<%= button_to "Remove Admin", toggle_user_url(user), :method => :put, :class => "btn btn-mini btn-primary" %>
						</li>
					<% end %>
			<% end %>
		<% end %>
	</ul>
</div>

app/views/users/new.html.erb
<div class="span4 center">
	<br><br>
	<div class="inner-body">
		<h3>Create User</h3>

		<%= render :partial => "layouts/errors" %>

		<form action="<%= users_url %>" method="post" accept-charset="utf-8">
			<input type="hidden" 
						 name="authenticity_token"
						 value="<%= form_authenticity_token %>">
				 
			<label for="user-username">Username: </label>
			<input type="text" name="user[username]"
						 value="<%= @user.username %>" id="user-username">
			<br>
	
			<label for="user-email">Email: </label>
			<input type="text" name="user[email]"
						 value="<%= @user.email %>" id="user-email">
			<br>
	
			<label for="user-password">Password: </label>
			<input type="password" name="user[password]" id="user-password">
			<br>

			<label for="user-repeat">Confirm Password: </label>
			<input type="password" name="user[repeat]" id="user-repeat">
			<br>
	
			<label for="user-admin">
			<input type="checkbox" name="user[admin]" value="y" id="user-admin" "<%= "checked" if @user.admin %>">
			Administrator?</label>
	
			<p><input class="btn" type="submit" value="Create User"></p>
		</form>
	</div>
</div>

app/views/users/show.html.erb
<div class="inner-body">
	<% if current_user.admin %>
		<div class="pull-right">
			<%= button_to "New User", new_user_url, :method => :get, :class => "btn btn-info" %>
		</div>
	<% end %>
	<h3>User Manager</h3>
	<div class="row">
		<div class="span4">
			<%= render :partial => "user", :collection => current_account.users %>
		</div>
		<div class="span">
		</div>
		<div class="span4">
			<%= render :partial => "edit"%>
		</div>
	</div>
</div>