config/routes.rb
WufooClone::Application.routes.draw do
  root :to => "static_pages#root"
  
  resource :session, :only => [:new, :create, :destroy]
  resources :users, :except => [:index]
  resources :accounts, :only => [:new, :create, :show] do
    resources :users, :only => [:index]
  end
  
  resources :forms do
    resources :fields, :except => [:index, :show]
    resources :entries, :only => [:index, :new]
  end
  
  resources :entries, :except => [:new, :index]

  post "forms/:id/duplicate", :to => "forms#duplicate", :as => "duplicate_form"
  put "users/:id/toggle", :to=> "users#toggle_admin", :as => "toggle_user"
  get "help", :to => "static_pages#help"
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_filter :require_current_user!
  
  def index
    @forms = current_account.forms
    render :index
  end
  
  def show
    @form = Form.find(params[:id])
    render :show
  end
  
  def new
    render :new
  end
  
  def create
    params[:form][:account_id] = current_account.id
    fields = []
    
    if params[:fields]
      params[:fields].each do |key, val|
        field = Field.new(val[val.keys[0]])
        fields << field
      end
    end
    
    params[:form][:fields] = fields
    @form = Form.new(params[:form])
    p @form.fields
    if @form.save
      render :json => {}
    else
      errors = {}
      @form.errors.delete(:fields)
      errors[:form] = @form.errors.messages
      
      @form.fields.each_with_index do |field, i|
        errors[("field-" + i.to_s).to_sym] = field.errors.messages
      end

      p errors
      render :json => errors
    end
  end
  
  def edit
    @form = Form.find(params[:id])
    render :edit
  end
  
  def update
    @form = Form.find(params[:id])
    fields = []
    
    if params[:fields]
      params[:fields].each do |key, val|
        field = Field.new(val[val.keys[0]])
        fields << field
      end
    end
    
    params[:form][:fields] = fields
    
    if @form.update_attributes(params[:form])
      render :json => {}
    else
      errors = {}
      @form.errors.delete(:fields)
      errors[:form] = @form.errors.messages
      
      @form.fields.each_with_index do |field, i|
        errors[("field-" + i.to_s).to_sym] = field.errors.messages
      end
      
      render :json => errors
    end
  end
  
  def duplicate
    old_form = Form.find(params[:id])
    fields = old_form.fields.map {|field| Field.dup(field) }
    
    attributes = old_form.attributes
    attributes.delete("_id")
    attributes[:fields] = fields
    
    Form.create(attributes)
      
    redirect_to forms_url
  end
  
  def destroy
    @form = Form.find(params[:id])
    @form.destroy
    
    redirect_to forms_url
  end
end

app/helpers/forms_helper.rb
module FormsHelper
  def create_tag(field_id)
    "entry[" + field_id + "]"
  end
  
  def get_selections(field)
    selections = []
    
    field.choices.each do |choice|
      selections << [choice, choice]
    end
    
    selections
  end
  
  def radio_tag(field_id, val)
    "entry_" + field_id + "_" + val.downcase
  end
  
  def checkbox_tag(field_id, val)
    field_id.to_s + "[" + val.downcase + "]"
  end
  
  def checkbox_id(field_id, val)
    field_id.to_s + "_" + val.downcase
  end
  
  def checkbox_name(field_id)
    "entry[" + field_id + "][]"
  end
  
  def labels_to_display(form)
    fields = []
    form.fields.each_with_index do |field, i|
      fields << field if i < 2
    end
    fields
  end
end

app/views/forms/_field.html.erb
<label class="bold"><%= field.label %></label>
<% if field.type == "text_field" %>
	<input type="text" disabled>
<% elsif field.type == "text_area" %>
	<textarea disabled></textarea>
<% elsif field.type == "check_box" %>
	<% field.choices.each_with_index do |choice, i| %>
		<div class="choices">
			<div class="choice-<%= i %>">
				<label class="label"><%= choice %></label>
				<input type="checkbox" disabled>
			</div>
	<% end %>
<% elsif field.type == "select" %>
	<select id="select" disabled>
		<% field.choices.each_with_index do |choice, i| %>
			<option id="choice-<%= i %>"><%= choice %></option>
		<% end %>
	</select>
	<% else %>
	<div class="choices">
		<% field.choices.each_with_index do |choice, i| %>
			<div class="choice-<%= i %>">
				<label class="label"><%= choice %></label>
				<input id="first<%= i %>" type="radio" disabled>
			</div>
		<% end %>
	</div>
<% end %>

app/views/forms/_field_form.html.erb
<form id="field-<%= index %>" class="hidden-field-form">
	<input type="hidden" name="field_<%= index %>[type]" value="<%= field.type %>">
	
	<label for="label-<%= index %>">Label: </label>
	<input type="text" name="field_<%= index %>[label]" value="<%= field.label %>" id="label-<%= index %>">
	<br>
	
	<label class="label" for="field-required">Required</label>
	<input type="checkbox" name="field_<%= index %>[required]" value="t" id="field-required">
	<br>
	
	<label class="label" for="field-unique">No Duplicates</label>
	<input type="checkbox" name="field_<%= index %>[uniqueness]" value="t" id="field-unique">
	<br>
	
	<% if(field.type != "text_area" && field.type != "text_field") %>
		<% field.choices.each do |choice| %>
		<input type="text" name="field_<%= index %>[choices][]" value="<%= choice %>">
		<% end %>
	<% end %>
	<br>
	
	<input type="submit" class= "btn btn-primary" value="Save">
</form>

<script>
$(document).ready(function() {
	$("#field-<%= index %>").on("submit", function(event) {
		event.preventDefault();
		
		var data = $(event.target).serializeJSON();
		field = data.field_<%= index %>;
		$("li.field-<%= index %> label.bold").text(field.label);
		
		if (field.type == "select") {
			for (var i = 1; i <= field.choices.length; i++) {
				
				$("li.field-<%= index %> #select #choice-" + i).text(field.choices[i-1]);
			}
		}
		else if (field.type == "radio_button" || field.type == "check_box") {
			for (var i = 1; i <= field.choices.length; i++) {
				$("li.field-<%= index %> .choices .choice-" + i + " label").text(field.choices[i-1]);
			}
			
		}
	});
});
</script>

app/views/forms/_form.html.erb
<div class="el-show">
	<h4 class= "el-title"><%= form.title %></h4>
	<ul class="inline">
		<li><%= link_to "Entries", form_entries_url(form), :method => :get %></li>
		<li><%= link_to "Edit", edit_form_url(form), :method => :get %></li>
		<li><%= link_to "View", new_form_entry_url(form), :method => :get %></li>
		<li><%= link_to "Notifications" %></li>
		<li><%= link_to "Payment" %></li>
		<li><%= link_to "Code" %></li>
		<% if current_user.admin %>
			<li class="pull-right">
				<%= button_to "Delete", form_url(form), :method => :delete, :class => "btn btn-mini btn-danger"%>
			</li>
			<li class="pull-right">
				<%= button_to "Duplicate", duplicate_form_url(form), :method => :post, :class => "btn btn-mini btn-success"%>
			</li>
		<% end %>
	</ul>
	
</div>
<br>

app/views/forms/display.html.erb
<h2><%= @form.title%></h2>
<%= @form.description %>
<br>
<br>
<%= form_tag entries_url do %>
<input type="hidden" name="entry[form_id]" value="<%= @form.id %>">

	<% @form.fields.each do |field| %>
		<% if field.type == "check_box" %>
			<%= field.label %>
			<br>
			
			<% field.choices.each do |opt| %>
				
				<%= label_tag(create_special_tag(create_tag(field.id), opt), opt) %>
				<%= send field.type + '_tag', create_special_tag(create_tag(field.id), opt) %>
				<br>
			<% end %>
			
		<% elsif field.type == "radio_button" %>
			<%= field.label %>
			<br>
			
			<% field.choices.each do |opt| %>
				
				<%= label_tag(create_special_tag(create_tag(field.id), opt), opt) %>
				<%= send field.type + '_tag', create_tag(field.id), opt %>
				<br>
			<% end %>
			
		<% elsif field.type == "select" %>
			<%= field.label %>:
			<%= send field.type + '_tag', create_tag(field.id), options_for_select(get_selections(field)) %>
			<br>
			
		<% else %>
			<%= label_tag(create_tag(field.id), field.label) %>
	 		<%= send field.type + '_tag', create_tag(field.id) %>
		<% end %>
		<br>
		
	<% end %>
	
	<%= submit_tag "Submit" %>
<% end %>

app/views/forms/edit.html.erb
<div class="inner-body">
	
	<ul class="errors"></ul>
	
	<div class= "new-form-body">
		<div class="form-toolbar">
			<ul id="myTab" class="nav nav-tabs">
				<li class="add-field-tab active">
					<a href="#add-field" data-toggle="tab">Add a Field</a>
				</li>
				<li class="edit-field-tab">
					<a href="#edit-field" data-toggle="tab">Field Settings</a>
				</li>
				<li class="edit-form-tab">
					<a href="#edit-form" data-toggle="tab">Form Settings</a>
				</li>
			</ul>
			<div id="myTabContent" class="tab-content">
				<div id="add-field" class="tab-pane fade active in">
					<div class="tab-form">
						<h4>Standard Fields</h4>
						<button id="text-field-btn" class="btn btn-list" type="button">Single Line Text</button>
						<button id="text-area-btn" class="btn btn-list" type="button">Paragraph Text</button>
						<br>
						<br>
						<button id="checkbox-btn" class="btn btn-list" type="button">Checkbox</button>
						<button id="dropdown-btn" class="btn btn-list" type="button">Dropdown</button>
						<br>
						<br>
						<button id="radio-btn" class="btn btn-list" type="button">Multiple Choice</button>
					</div>
				</div>
				<div id="edit-field" class="tab-pane fade" data-id="<%= @form.fields.length %>">
					<div class="tab-form">
						<% @form.fields.each_with_index do |field, i| %>
								<%=render :partial => "field_form", :locals => {:field => field, :index => i} %>
						<% end %>
					</div>
				</div>
				<div id="edit-form" class="tab-pane fade">
					<div class="tab-form">
						<form id="save-form-attributes">
							<label for="form-title-attr">Form Title: </label>
							<input type="text" name="form[title]" value="<%= @form.title %>" id="form-title-attr">
							<br>
							<label for="form-description-attr">Form Description: </label>
							<textarea id="form-description-attr" name="form[description]" value="<%= @form.description %>" rows="4"></textarea>
							<br>
	
							<input type="submit" class="btn btn-primary" value="Save">
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="new-form">
			<div id="form" data-id="<%= @form.id %>">
				<h3 id="form-title"><%= @form.title %></h3>
				<p id="form-description"><%= @form.description %></p>
			</div>
			
				<ul id="fields">
					<% @form.fields.each_with_index do |field, i| %>
						<li class="field-<%= i %>">
							<%=render :partial => "field", :locals => {:field => field} %>
						</li>
					<% end %>
				</ul>
			
		</div>
		<div id="update-form">
			<button id="update-form-btn" class="btn btn-primary pull-right" type="submit">Update Form</button>
			<br>
		</div>
	</div>
</div>

app/views/forms/index.html.erb
<div class="inner-body">
	<% if current_user.admin %>
		<div class="pull-right">
			<%= button_to "New Form", new_form_url, :method => :get, :class => "btn btn-info" %>
		</div>
	<% end %>
	<h3>Form Manager</h3>
	<br>

	<%= render :partial => "form", :collection => @forms %>
</div>

app/views/forms/new.html.erb
<div class="inner-body">
	
	<ul class="errors"></ul>
	
	<div class= "new-form-body">
		<div class="form-toolbar">
			<ul id="myTab" class="nav nav-tabs">
				<li class="add-field-tab active">
					<a href="#add-field" data-toggle="tab">Add a Field</a>
				</li>
				<li class="edit-field-tab">
					<a href="#edit-field" data-toggle="tab">Field Settings</a>
				</li>
				<li class="edit-form-tab">
					<a href="#edit-form" data-toggle="tab">Form Settings</a>
				</li>
			</ul>
			<div id="myTabContent" class="tab-content">
				<div id="add-field" class="tab-pane fade active in">
					<div class="tab-form">
						<h4>Standard Fields</h4>
						<button id="text-field-btn" class="btn btn-list" type="button">Single Line Text</button>
						<button id="text-area-btn" class="btn btn-list" type="button">Paragraph Text</button>
						<br>
						<br>
						<button id="checkbox-btn" class="btn btn-list" type="button">Checkbox</button>
						<button id="dropdown-btn" class="btn btn-list" type="button">Dropdown</button>
						<br>
						<br>
						<button id="radio-btn" class="btn btn-list" type="button">Multiple Choice</button>
					</div>
				</div>
				<div id="edit-field" class="tab-pane fade">
					<div class="tab-form">
						<!-- append field forms onto tab-form -->
					</div>
				</div>
				<div id="edit-form" class="tab-pane fade">
					<div class="tab-form">
						<form id="save-form-attributes">
							<label for="form-title-attr">Form Title: </label>
							<input type="text" name="form[title]" value="Untitled" id="form-title-attr">
							<br>
							<label for="form-description-attr">Form Description: </label>
							<textarea id="form-description-attr" name="form[description]" rows="4">Create a new form!</textarea>
							<br>
	
							<input type="submit" class="btn btn-primary" value="Save">
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="new-form">
			<div id="form">
				<h3 id="form-title">Untitled Form</h3>
				<p id="form-description">Create a new form!</p>
			</div>
			
				<ul id="fields"></ul>
			
		</div>
		<div id="create-form">
			<button id="create-form-btn" class="btn btn-primary pull-right" type="submit">Make Form</button>
			<br>
		</div>
	</div>
</div>