config/routes.rb
WufooClone::Application.routes.draw do
  root :to => "static_pages#root"
  
  resource :session, :only => [:new, :create, :destroy]
  resources :users, :except => [:index]
  resources :accounts, :only => [:new, :create, :show] do
    resources :users, :only => [:index]
  end
  
  resources :forms do
    resources :fields, :except => [:index, :show]
    resources :entries, :only => [:index, :new]
  end
  
  resources :entries, :except => [:new, :index]

  post "forms/:id/duplicate", :to => "forms#duplicate", :as => "duplicate_form"
  put "users/:id/toggle", :to=> "users#toggle_admin", :as => "toggle_user"
  get "help", :to => "static_pages#help"
end

app/views/layouts/_errors.html.erb
<div>
	<% if flash.now[:errors] %>
		<% flash.now[:errors].each do |error| %>
		<%= error %><br>
		<% end %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WufooClone" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class= "icon-bar"></span>
						<span class= "icon-bar"></span>
						<span class= "icon-bar"></span>
						<span class= "icon-bar"></span>
						<span class= "icon-bar"></span>
						<span class= "icon-bar"></span>
					</a>
          <a class="brand" href="<%= forms_url %>"><strong>Clufoo</strong></a>
          <div class="container nav-collapse">
            <ul class="nav">
							<% if current_user %>
	              <li><a class="navbar-btn"><%= button_to "Forms", forms_url(current_user), :method => :get, :class => "btn btn-inverse" %></a></li>
	              <li><a class="navbar-btn"><%= button_to "Reports", forms_url(current_user), :method => :get, :class => "btn btn-inverse" %></a></li>
	              <li><a class="navbar-btn"><%= button_to "Users", user_url(current_user), :method => :get, :class => "btn btn-inverse" %></a></li>
	              <li><a class="navbar-btn"><%= button_to "Account", account_url(current_user.account_id), :method => :get, :class => "btn btn-inverse" %></a></li>
							<% end %>
            </ul>
						<ul class="nav pull-right">
							<li><a class="navbar-btn"><%= button_to "Help", help_url, :method => :get, :class => "btn btn-inverse" %></a></li>
							<% if current_user %>
								<li><a class="navbar-btn"><%= button_to "Logout", session_url, :method => :delete, :class => "btn btn-inverse" %></a></li>
							<% else %>
								<li><a class="navbar-btn"><%= button_to "Login", new_session_url, :method => :get, :class => "btn btn-inverse" %></a></li>
							<% end %>
						</ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="outer-body">
        <div>
          <%= yield %>
        </div>

      <footer>
      </footer>

    </div> <!-- /container -->

  </body>
</html>