config/routes.rb
WufooClone::Application.routes.draw do
  root :to => "static_pages#root"
  
  resource :session, :only => [:new, :create, :destroy]
  resources :users, :except => [:index]
  resources :accounts, :only => [:new, :create, :show] do
    resources :users, :only => [:index]
  end
  
  resources :forms do
    resources :fields, :except => [:index, :show]
    resources :entries, :only => [:index, :new]
  end
  
  resources :entries, :except => [:new, :index]

  post "forms/:id/duplicate", :to => "forms#duplicate", :as => "duplicate_form"
  put "users/:id/toggle", :to=> "users#toggle_admin", :as => "toggle_user"
  get "help", :to => "static_pages#help"
end

app/models/account.rb
class Account
  include MongoMapper::Document
  key :creator_id, ObjectId, :required => true
  
  many :forms
  many :users
  many :reports
  
  def is_creator?(user_id)
    creator_id == user_id
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:new, :create]
  before_filter :require_current_user!, :only => [:show]
  
  def show
    @account = current_account
    render :show
  end
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    if(params[:user][:password] == params[:user][:repeat])
      params[:user][:repeat] = nil
      params[:user][:admin] = 't'
      
      @account = Account.new
      params[:user][:account_id] = @account.id
      @user = User.new(params[:user])
      @account.creator_id = @user.id
      @account.save
      
      
      if @user.save
        self.current_user = @user
        redirect_to forms_url(current_account)
      else
        flash.now[:errors] = @user.errors.full_messages
        render :new
      end
    else
      flash.now[:errors] = ["Passwords do not match"]
      @user = User.new(params[:user])
      render :new
    end    
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_user.html.erb
<div class="el-show">
	<h4 class= "el-title"><%= user.username %></h4>
	<ul class="inline">
		<li><%= user.user_type %></li>
		<% if current_user.admin %>
			<%  unless current_account.is_creator?(user.id) %>
				<li class="pull-right">
					<%= button_to "Delete", user_url(user), :method => :delete, :class => "btn btn-mini btn-danger" %>
				</li>
					<% if user.user_type == "User" %>
						<li class="pull-right">
							<%= button_to "Make Admin", user_url(user), :method => :put, :class => "btn btn-mini btn-primary" %>
						</li>
					<% else %>
						<li class="pull-right">
							<%= button_to "Remove Admin", user_url(user), :method => :put, :class => "btn btn-mini btn-primary" %>
						</li>
					<% end %>
			<% end %>
		<% end %>
	</ul>
</div>

app/views/accounts/new.html.erb
<div class="span4 center">
	<br><br>
	<div class="inner-body">
		<h3>Sign Up</h3>

		<%= render :partial => "layouts/errors" %>
	
		<form action="<%= accounts_url %>" method="post" accept-charset="utf-8">
			<input type="hidden" 
						 name="authenticity_token"
						 value="<%= form_authenticity_token %>">
	
			<label for="user-username">Username: </label>
			<input type="text" name="user[username]"
						 value="<%= @user.username %>" id="user-username">
			<br>
	
			<label for="user-email">Email: </label>
			<input type="text" name="user[email]"
						 value="<%= @user.email %>" id="user-email">
			<br>
	
			<label for="user-password">Password: </label>
			<input type="password" name="user[password]" id="user-password">
			<br>

			<label for="user-repeat">Confirm Password: </label>
			<input type="password" name="user[repeat]" id="user-repeat">
			<br>
	
			<p><input class="btn" type="submit" value="Create Account"></p>
		</form>
	</div>
</div>

app/views/accounts/show.html.erb
<div class="inner-body">
	<h3>Account Manager</h3>
	Under Construction...
</div>